name: BuildNugetPackages

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab

  workflow_dispatch:
    inputs:
      publish:
        type: boolean
        description: 'Publish to nugget server'     
        required: false
        default: false

env:
  PROJECTDIR: 'Module\IPAddressHelper\Helpers' #folder where IPAddressHelper.csproj
  NUGET_SERVER: 'https://api.nuget.org/v3/index.json'
  NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  NUGETAPIKEY : ${{secrets.NUGET_APIKEY}}

jobs:
  publish:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v4 
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        source-url: ${{ env.NUGET_SERVER }}
          
    - name: Install dependencies
    #install required packeges
      run: |
        dotnet restore $env:PROJECTDIR 
    
    - name: Build
      run: |
        dotnet build --configuration Release --no-restore $env:PROJECTDIR

    - name: Install AzureSignTool
      shell: pwsh
      run: |
             dotnet tool install --global AzureSignTool

    - name: Sign files
      shell: pwsh
      run: |
               $files = Get-ChildItem "$env:PROJECTDIR\bin\Release\" -File -Recurse -Include *.dll
               try {
                   foreach ($file in $files) {
                       azuresigntool sign `
                           -kvu ${{ vars.CODESIGNING_KEYVAULTURI }} `
                           -kvi ${{ vars.TENANTINTEGRATION_CLIENTID }} `
                           -kvt ${{ vars.TENANTINTEGRATION_TENANTID }} `
                           -kvs ${{ secrets.TENANTINTEGRATION_CLIENTSECRET }} `
                           -kvc ${{ vars.CODESIGNING_CERTNAME }} `
                           -tr 'http://timestamp.digicert.com' `
                           -v "$($file.FullName)" 
                   }
               }
               catch {
                   Write-Host "Error: $($_.Exception)"
                   throw
               }
               Write-Host "Signed files summary:"
               Get-AuthenticodeSignature -FilePath $files

    - name: Package
      run: |
         dotnet pack --configuration Release $env:PROJECTDIR 

    - name: Publish the package
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.publish=='true' }}
      run: |
        dotnet nuget push $env:PROJECTDIR\bin\Release\*.nupkg -k $env:NUGETAPIKEY
